### ISSUE TITLE
Matrix version is not working

### ISSUE THREAD

**Issue by staycanuca** [Sphinxroot/plugin.video.IPTV.Matele.Direct#1]
Hy, matrix version have to many syntax error and some module error (urllib2, urlretrieve).
Can you fix this? I really wan to try your plugin on kodi 19.
Thanks!

**Comment by Sphinxroot** [comment]
sorrry i wont fixe it for now  as i need to edit every addon and dependencies files related to it to make it work  , for now it work on 18.9 leila  i will wait until other coder have updated everything arround
